export const listedCareHomes = [
  {
    id: '1',
    name: 'Sunrise Senior Living — Richmond',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 86,
    location: 'Richmond, Surrey',
    postcode: 'TW9 2PR',
    specialties: ['Dementia', 'Nursing', 'Residential'],
    phone: '020 8948 8844',
    shiftsPosted: 12,
    avgRate: 24.50,
  },
  {
    id: '2',
    name: 'Barchester Healthcare — Maida Vale',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 64,
    location: 'London, W9',
    postcode: 'W9 1NY',
    specialties: ['Nursing', 'Stroke Recovery', 'Palliative Care'],
    phone: '020 7286 2444',
    shiftsPosted: 18,
    avgRate: 26.50,
  },
  {
    id: '3',
    name: 'Care UK — Brighton Home',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 72,
    location: 'Brighton, East Sussex',
    postcode: 'BN2 0GE',
    specialties: ['Residential', 'Dementia', 'Mental Health'],
    phone: '01273 626 500',
    shiftsPosted: 8,
    avgRate: 22.00,
  },
  {
    id: '4',
    name: 'Bupa — Manchester Care Centre',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 95,
    location: 'Manchester, Greater Manchester',
    postcode: 'M1 3DA',
    specialties: ['Nursing', 'Rehabilitation', 'Dementia'],
    phone: '0161 236 8844',
    shiftsPosted: 15,
    avgRate: 24.00,
  },
  {
    id: '5',
    name: 'Hallmark Care Services — Bristol',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 78,
    location: 'Bristol, Gloucestershire',
    postcode: 'BS8 4PU',
    specialties: ['Residential', 'Nursing', 'Dementia'],
    phone: '0117 973 7000',
    shiftsPosted: 11,
    avgRate: 23.50,
  },
  {
    id: '6',
    name: 'Four Seasons Health Care — Edinburgh',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 88,
    location: 'Edinburgh, Scotland',
    postcode: 'EH3 5AA',
    specialties: ['Nursing', 'Dementia', 'End of Life Care'],
    phone: '0131 225 1800',
    shiftsPosted: 14,
    avgRate: 25.50,
  },
  {
    id: '7',
    name: 'HC-One — Leeds Care Home',
    type: 'Residential',
    cqcRating: 'Requires Improvement',
    beds: 65,
    location: 'Leeds, West Yorkshire',
    postcode: 'LS2 8JJ',
    specialties: ['Residential', 'Dementia'],
    phone: '0113 243 5555',
    shiftsPosted: 20,
    avgRate: 21.50,
  },
  {
    id: '8',
    name: 'Dolce Vita Nursing Home — London',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 52,
    location: 'Kensington, London',
    postcode: 'SW5 9JZ',
    specialties: ['Nursing', 'Specialist Care'],
    phone: '020 7591 1234',
    shiftsPosted: 9,
    avgRate: 28.00,
  },
  {
    id: '9',
    name: 'Anchor Care — Glasgow',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 70,
    location: 'Glasgow, Scotland',
    postcode: 'G2 1BD',
    specialties: ['Residential', 'Older Adults', 'Support'],
    phone: '0141 248 8000',
    shiftsPosted: 10,
    avgRate: 22.50,
  },
  {
    id: '10',
    name: 'Colten Care — Dorset',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 82,
    location: 'Dorchester, Dorset',
    postcode: 'DT1 2LA',
    specialties: ['Nursing', 'Dementia', 'Rehabilitation'],
    phone: '01305 262 000',
    shiftsPosted: 13,
    avgRate: 25.00,
  },
  {
    id: '11',
    name: 'Priory Care Services — Birmingham',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 76,
    location: 'Birmingham, West Midlands',
    postcode: 'B5 6AD',
    specialties: ['Nursing', 'Residential', 'Dementia'],
    phone: '0121 633 3333',
    shiftsPosted: 16,
    avgRate: 23.50,
  },
  {
    id: '12',
    name: 'Orchard Care Group — Norfolk',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 60,
    location: 'Norwich, Norfolk',
    postcode: 'NR1 1GS',
    specialties: ['Residential', 'Dementia Support'],
    phone: '01603 622 700',
    shiftsPosted: 7,
    avgRate: 21.00,
  },
  {
    id: '13',
    name: 'Kindred Care — Manchester',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 71,
    location: 'Stockport, Greater Manchester',
    postcode: 'SK1 4PT',
    specialties: ['Nursing', 'Wound Care', 'Dementia'],
    phone: '0161 480 8844',
    shiftsPosted: 12,
    avgRate: 24.00,
  },
  {
    id: '14',
    name: 'Ashton Court Care Centre — Somerset',
    type: 'Residential',
    cqcRating: 'Outstanding',
    beds: 55,
    location: 'Taunton, Somerset',
    postcode: 'TA1 3AU',
    specialties: ['Residential', 'Dementia', 'Holistic Care'],
    phone: '01823 277 000',
    shiftsPosted: 6,
    avgRate: 22.50,
  },
  {
    id: '15',
    name: 'Meridian Care — West London',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 68,
    location: 'Hammersmith, London',
    postcode: 'W6 9QY',
    specialties: ['Nursing', 'Rehabilitation', 'End of Life'],
    phone: '020 8741 5500',
    shiftsPosted: 14,
    avgRate: 27.50,
  },
  {
    id: '16',
    name: 'Synergy Care — Southampton',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 79,
    location: 'Southampton, Hampshire',
    postcode: 'SO14 3TL',
    specialties: ['Nursing', 'Residential', 'Memory Care'],
    phone: '023 8033 5555',
    shiftsPosted: 11,
    avgRate: 23.00,
  },
  {
    id: '17',
    name: 'Eden House Care — Kent',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 66,
    location: 'Canterbury, Kent',
    postcode: 'CT1 2BB',
    specialties: ['Nursing', 'Elderly Care', 'Dementia'],
    phone: '01227 464 700',
    shiftsPosted: 9,
    avgRate: 22.50,
  },
  {
    id: '18',
    name: 'Westbury Care — Devon',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 62,
    location: 'Exeter, Devon',
    postcode: 'EX1 2PG',
    specialties: ['Residential', 'Dementia', 'Respite Care'],
    phone: '01392 411 000',
    shiftsPosted: 8,
    avgRate: 21.50,
  },
  {
    id: '19',
    name: 'Richmond Care Home — York',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 74,
    location: 'York, North Yorkshire',
    postcode: 'YO1 9QN',
    specialties: ['Nursing', 'Dementia Care', 'Community Integration'],
    phone: '01904 649 000',
    shiftsPosted: 10,
    avgRate: 24.50,
  },
  {
    id: '20',
    name: 'Oakwood Care Home — Berkshire',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 84,
    location: 'Windsor, Berkshire',
    postcode: 'SL4 1RJ',
    specialties: ['Nursing', 'Residential', 'Specialist Dementia Unit'],
    phone: '01753 854 300',
    shiftsPosted: 13,
    avgRate: 25.00,
  },
  {
    id: '21',
    name: 'Serenity Care Home — Liverpool',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 72,
    location: 'Liverpool, Merseyside',
    postcode: 'L3 9AG',
    specialties: ['Nursing', 'Dementia', 'Stroke Recovery'],
    phone: '0151 236 2000',
    shiftsPosted: 15,
    avgRate: 24.50,
  },
  {
    id: '22',
    name: 'Valley View Residential — Swansea',
    type: 'Residential',
    cqcRating: 'Outstanding',
    beds: 68,
    location: 'Swansea, Wales',
    postcode: 'SA1 1LY',
    specialties: ['Residential', 'Dementia', 'Memory Care'],
    phone: '01792 656 500',
    shiftsPosted: 10,
    avgRate: 23.00,
  },
  {
    id: '23',
    name: 'Heritage Care Centre — Belfast',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 76,
    location: 'Belfast, Northern Ireland',
    postcode: 'BT2 7EA',
    specialties: ['Nursing', 'Residential', 'Mental Health'],
    phone: '028 9024 5555',
    shiftsPosted: 12,
    avgRate: 24.00,
  },
  {
    id: '24',
    name: 'Glenworth Nursing — Aberdeen',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 65,
    location: 'Aberdeen, Scotland',
    postcode: 'AB10 1BD',
    specialties: ['Nursing', 'Rehabilitation', 'End of Life Care'],
    phone: '01224 573 000',
    shiftsPosted: 9,
    avgRate: 25.50,
  },
  {
    id: '25',
    name: 'Prospect House — Coventry',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 58,
    location: 'Coventry, West Midlands',
    postcode: 'CV1 2GE',
    specialties: ['Residential', 'Palliative Care', 'Dementia'],
    phone: '024 7622 1111',
    shiftsPosted: 7,
    avgRate: 22.00,
  },
  {
    id: '26',
    name: 'Bridgewater Care — Reading',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 82,
    location: 'Reading, Berkshire',
    postcode: 'RG1 2BZ',
    specialties: ['Nursing', 'Stroke Recovery', 'Specialist Care'],
    phone: '0118 956 7700',
    shiftsPosted: 14,
    avgRate: 26.50,
  },
  {
    id: '27',
    name: 'Meadowbrook Residential — Wakefield',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 70,
    location: 'Wakefield, West Yorkshire',
    postcode: 'WF1 3QH',
    specialties: ['Residential', 'Dementia', 'Respite Care'],
    phone: '01924 311 900',
    shiftsPosted: 11,
    avgRate: 21.50,
  },
  {
    id: '28',
    name: 'Riverside Care Home — Chelmsford',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 79,
    location: 'Chelmsford, Essex',
    postcode: 'CM2 0GB',
    specialties: ['Nursing', 'Residential', 'Learning Disabilities'],
    phone: '01245 400 300',
    shiftsPosted: 13,
    avgRate: 24.50,
  },
  {
    id: '29',
    name: 'Royal Oaks Nursing — Dunfermline',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 75,
    location: 'Dunfermline, Scotland',
    postcode: 'KY11 8QL',
    specialties: ['Nursing', 'Palliative Care', 'Complex Care'],
    phone: '01383 722 000',
    shiftsPosted: 10,
    avgRate: 25.00,
  },
  {
    id: '30',
    name: 'Meadows Care Home — Newport',
    type: 'Residential',
    cqcRating: 'Requires Improvement',
    beds: 62,
    location: 'Newport, Wales',
    postcode: 'NP19 8QG',
    specialties: ['Residential', 'Physical Disabilities', 'Rehabilitation'],
    phone: '01633 840 500',
    shiftsPosted: 8,
    avgRate: 20.50,
  },
  {
    id: '31',
    name: 'Northaven Residential Care — Sheffield',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 87,
    location: 'Sheffield, South Yorkshire',
    postcode: 'S3 8GB',
    specialties: ['Nursing', 'Residential', 'Dementia', 'Wound Care'],
    phone: '0114 275 6666',
    shiftsPosted: 16,
    avgRate: 24.00,
  },
  {
    id: '32',
    name: 'Silverstone Care — Sunderland',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 71,
    location: 'Sunderland, Tyne and Wear',
    postcode: 'SR1 3QF',
    specialties: ['Nursing', 'Memory Care', 'End of Life Care'],
    phone: '0191 510 3000',
    shiftsPosted: 11,
    avgRate: 24.50,
  },
  {
    id: '33',
    name: 'Greenacres Residential — Slough',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 64,
    location: 'Slough, Berkshire',
    postcode: 'SL1 2BG',
    specialties: ['Residential', 'Mental Health', 'Behavioral Support'],
    phone: '01753 526 700',
    shiftsPosted: 9,
    avgRate: 22.50,
  },
  {
    id: '34',
    name: 'Parkland Care Home — Inverness',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 60,
    location: 'Inverness, Scotland',
    postcode: 'IV2 4JF',
    specialties: ['Nursing', 'Elderly Care', 'Rehabilitation'],
    phone: '01463 227 300',
    shiftsPosted: 7,
    avgRate: 24.00,
  },
  {
    id: '35',
    name: 'Harmony Care Centre — Durham',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 77,
    location: 'Durham, County Durham',
    postcode: 'DH1 3AU',
    specialties: ['Nursing', 'Residential', 'Dementia', 'Respite Care'],
    phone: '0191 386 7700',
    shiftsPosted: 12,
    avgRate: 23.50,
  },
  {
    id: '36',
    name: 'Sunset Views Nursing — Bangor',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 73,
    location: 'Bangor, Wales',
    postcode: 'LL57 2DZ',
    specialties: ['Nursing', 'Stroke Recovery', 'Dementia'],
    phone: '01248 353 000',
    shiftsPosted: 10,
    avgRate: 23.00,
  },
  {
    id: '37',
    name: 'Cornerstone Residential — Derry',
    type: 'Residential',
    cqcRating: 'Outstanding',
    beds: 59,
    location: 'Derry, Northern Ireland',
    postcode: 'BT48 6AD',
    specialties: ['Residential', 'Learning Disabilities', 'Specialist Care'],
    phone: '028 7126 4444',
    shiftsPosted: 6,
    avgRate: 21.00,
  },
  {
    id: '38',
    name: 'Lakeside Care Home — Stoke',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 80,
    location: 'Stoke-on-Trent, Staffordshire',
    postcode: 'ST4 6DJ',
    specialties: ['Nursing', 'Residential', 'Mental Health Support'],
    phone: '01782 744 500',
    shiftsPosted: 14,
    avgRate: 23.50,
  },
  {
    id: '39',
    name: 'Willowbrook Nursing — Bournemouth',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 69,
    location: 'Bournemouth, Dorset',
    postcode: 'BH2 6BN',
    specialties: ['Nursing', 'Palliative Care', 'Specialist Wound Care'],
    phone: '01202 552 200',
    shiftsPosted: 11,
    avgRate: 25.50,
  },
  {
    id: '40',
    name: 'Trinity Care Home — Lincoln',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 66,
    location: 'Lincoln, Lincolnshire',
    postcode: 'LN1 1ER',
    specialties: ['Residential', 'Dementia', 'Companionship Support'],
    phone: '01522 501 600',
    shiftsPosted: 8,
    avgRate: 21.50,
  },
  {
    id: '41',
    name: 'Crescent Nursing Home — Perth',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 74,
    location: 'Perth, Scotland',
    postcode: 'PH1 5TT',
    specialties: ['Nursing', 'Dementia', 'End of Life Care'],
    phone: '01738 630 000',
    shiftsPosted: 13,
    avgRate: 25.50,
  },
  {
    id: '42',
    name: 'Sunny Gardens Residential — Swindon',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 61,
    location: 'Swindon, Wiltshire',
    postcode: 'SN1 1DZ',
    specialties: ['Residential', 'Physical Disabilities', 'Dementia'],
    phone: '01793 410 200',
    shiftsPosted: 9,
    avgRate: 22.00,
  },
  {
    id: '43',
    name: 'Westfield Care Centre — Armagh',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 78,
    location: 'Armagh, Northern Ireland',
    postcode: 'BT60 1ER',
    specialties: ['Nursing', 'Residential', 'Memory Care'],
    phone: '028 3751 2222',
    shiftsPosted: 11,
    avgRate: 24.00,
  },
  {
    id: '44',
    name: 'Moorfield Nursing — Wolverhampton',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 67,
    location: 'Wolverhampton, West Midlands',
    postcode: 'WV1 4DH',
    specialties: ['Nursing', 'Rehabilitation', 'Complex Care'],
    phone: '01902 355 400',
    shiftsPosted: 10,
    avgRate: 23.50,
  },
  {
    id: '45',
    name: 'Ashford Care Home — Medway',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 63,
    location: 'Medway, Kent',
    postcode: 'ME4 5BT',
    specialties: ['Residential', 'Dementia', 'Respite Care'],
    phone: '01634 723 300',
    shiftsPosted: 8,
    avgRate: 22.50,
  },
  {
    id: '46',
    name: 'Clover Nursing Home — Stirling',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 70,
    location: 'Stirling, Scotland',
    postcode: 'FK8 2BN',
    specialties: ['Nursing', 'Stroke Recovery', 'End of Life Care'],
    phone: '01786 464 000',
    shiftsPosted: 11,
    avgRate: 24.50,
  },
  {
    id: '47',
    name: 'Penrose Residential — Cardiff',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 85,
    location: 'Cardiff, Wales',
    postcode: 'CF10 3BY',
    specialties: ['Nursing', 'Residential', 'Dementia', 'Palliative Care'],
    phone: '029 2023 5000',
    shiftsPosted: 15,
    avgRate: 24.50,
  },
  {
    id: '48',
    name: 'Highfield Care Home — Wigan',
    type: 'Nursing Home',
    cqcRating: 'Outstanding',
    beds: 68,
    location: 'Wigan, Greater Manchester',
    postcode: 'WN3 5DF',
    specialties: ['Nursing', 'Memory Care', 'Specialist Care'],
    phone: '01942 833 200',
    shiftsPosted: 12,
    avgRate: 24.00,
  },
  {
    id: '49',
    name: 'Eastview Residential — Northampton',
    type: 'Residential',
    cqcRating: 'Good',
    beds: 75,
    location: 'Northampton, Northamptonshire',
    postcode: 'NN1 5AU',
    specialties: ['Residential', 'Mental Health', 'Learning Disabilities'],
    phone: '01604 250 500',
    shiftsPosted: 10,
    avgRate: 21.50,
  },
  {
    id: '50',
    name: 'Goldwyn Nursing Care — Falkirk',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 72,
    location: 'Falkirk, Scotland',
    postcode: 'FK1 1RQ',
    specialties: ['Nursing', 'Dementia', 'Rehabilitation'],
    phone: '01324 611 000',
    shiftsPosted: 9,
    avgRate: 25.00,
  },
  {
    id: '51',
    name: 'Ridgeway Care Home — Wrexham',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 81,
    location: 'Wrexham, Wales',
    postcode: 'LL13 8BX',
    specialties: ['Nursing', 'Residential', 'Stroke Recovery'],
    phone: '01978 265 500',
    shiftsPosted: 12,
    avgRate: 23.50,
  },
  {
    id: '52',
    name: 'Maple Lodge Nursing — Lisburn',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 66,
    location: 'Lisburn, Northern Ireland',
    postcode: 'BT27 4UG',
    specialties: ['Nursing', 'Palliative Care', 'End of Life Care'],
    phone: '028 9266 8888',
    shiftsPosted: 10,
    avgRate: 23.50,
  },
  {
    id: '53',
    name: 'Harvest Fields Residential — Ipswich',
    type: 'Residential',
    cqcRating: 'Outstanding',
    beds: 57,
    location: 'Ipswich, Suffolk',
    postcode: 'IP1 2JJ',
    specialties: ['Residential', 'Dementia', 'Specialist Care'],
    phone: '01473 255 700',
    shiftsPosted: 7,
    avgRate: 22.50,
  },
  {
    id: '54',
    name: 'Pinnacle Care Home — Peterborough',
    type: 'Residential & Nursing',
    cqcRating: 'Good',
    beds: 83,
    location: 'Peterborough, Cambridgeshire',
    postcode: 'PE1 1SG',
    specialties: ['Nursing', 'Residential', 'Memory Care', 'Respite Care'],
    phone: '01733 564 200',
    shiftsPosted: 13,
    avgRate: 24.00,
  },
  {
    id: '55',
    name: 'Evergreen Nursing — Paisley',
    type: 'Nursing Home',
    cqcRating: 'Good',
    beds: 76,
    location: 'Paisley, Scotland',
    postcode: 'PA1 2NE',
    specialties: ['Nursing', 'Dementia', 'Wound Management'],
    phone: '0141 840 5555',
    shiftsPosted: 11,
    avgRate: 25.50,
  },
];

export const listedProfessionals = [
  {
    id: '1',
    initials: 'AO',
    name: 'Amara O.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Birmingham',
    specialties: ['Critical Care', 'A&E'],
    yearsExperience: 8,
    rating: 4.9,
    shiftsCompleted: 142,
    hourlyRate: { min: 24, max: 28 },
    availability: 'Mon-Fri',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '2',
    initials: 'JM',
    name: 'James M.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'London',
    specialties: ['Personal Care', 'Dementia', 'Mobility Support'],
    yearsExperience: 3,
    rating: 4.7,
    shiftsCompleted: 87,
    hourlyRate: { min: 12.71, max: 14 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '3',
    initials: 'RS',
    name: 'Roslyn S.',
    role: 'Senior Care Worker',
    band: 'Band 3',
    location: 'Manchester',
    specialties: ['Residential Care', 'Behavioral Support', 'Safeguarding'],
    yearsExperience: 12,
    rating: 4.8,
    shiftsCompleted: 267,
    hourlyRate: { min: 15, max: 17 },
    availability: 'Weekends',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '4',
    initials: 'DK',
    name: 'Daniel K.',
    role: 'Registered Nurse',
    band: 'Band 7',
    location: 'Leeds',
    specialties: ['Wound Management', 'Infection Control', 'Training'],
    yearsExperience: 15,
    rating: 4.9,
    shiftsCompleted: 189,
    hourlyRate: { min: 28, max: 32 },
    availability: 'Mon-Fri',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '5',
    initials: 'PC',
    name: 'Priya C.',
    role: 'Support Worker',
    band: 'Band 2',
    location: 'Brighton',
    specialties: ['Mental Health Support', 'Domestic Assistance', 'Companionship'],
    yearsExperience: 4,
    rating: 4.6,
    shiftsCompleted: 65,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '6',
    initials: 'MH',
    name: 'Mohammed H.',
    role: 'Nursing Assistant',
    band: 'Band 2',
    location: 'Bristol',
    specialties: ['Patient Hygiene', 'Mobility', 'Feeding Support'],
    yearsExperience: 2,
    rating: 4.5,
    shiftsCompleted: 48,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '7',
    initials: 'EG',
    name: 'Elena G.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Edinburgh',
    specialties: ['Palliative Care', 'Dementia', 'Family Support'],
    yearsExperience: 10,
    rating: 4.9,
    shiftsCompleted: 156,
    hourlyRate: { min: 25, max: 29 },
    availability: 'Mon-Fri, Weekends',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '8',
    initials: 'TL',
    name: 'Thomas L.',
    role: 'Care Coordinator',
    band: 'Band 3',
    location: 'Manchester',
    specialties: ['Shift Management', 'Staff Training', 'Care Planning'],
    yearsExperience: 8,
    rating: 4.7,
    shiftsCompleted: 124,
    hourlyRate: { min: 16, max: 18 },
    availability: 'Mon-Fri',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '9',
    initials: 'SK',
    name: 'Sophia K.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'London',
    specialties: ['Domestic Support', 'Meal Preparation', 'Laundry'],
    yearsExperience: 1,
    rating: 4.4,
    shiftsCompleted: 32,
    hourlyRate: { min: 12.71, max: 13 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '10',
    initials: 'CB',
    name: 'Christopher B.',
    role: 'Senior Registered Nurse',
    band: 'Band 7',
    location: 'Cardiff',
    specialties: ['Hospital Discharge Planning', 'Complex Care', 'Leadership'],
    yearsExperience: 18,
    rating: 4.9,
    shiftsCompleted: 203,
    hourlyRate: { min: 29, max: 33 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '11',
    initials: 'NP',
    name: 'Nadia P.',
    role: 'Live-in Carer',
    band: 'N/A',
    location: 'Guildford',
    specialties: ['Live-in Care', 'Personal Care', '24/7 Support'],
    yearsExperience: 6,
    rating: 4.8,
    shiftsCompleted: 78,
    hourlyRate: { min: 18, max: 22 },
    availability: 'Live-in',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '12',
    initials: 'VD',
    name: 'Victor D.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Belfast',
    specialties: ['Occupational Health', 'Rehabilitation', 'Exercise Support'],
    yearsExperience: 5,
    rating: 4.6,
    shiftsCompleted: 91,
    hourlyRate: { min: 13, max: 15 },
    availability: 'Weekdays',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '13',
    initials: 'LP',
    name: 'Lucia P.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Cambridge',
    specialties: ['Acute Care', 'Documentation', 'Clinical Governance'],
    yearsExperience: 7,
    rating: 4.7,
    shiftsCompleted: 118,
    hourlyRate: { min: 23, max: 27 },
    availability: 'Mon-Fri, On-call',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '14',
    initials: 'RJ',
    name: 'Rajesh J.',
    role: 'Senior Care Worker',
    band: 'Band 4',
    location: 'Leicester',
    specialties: ['Cultural Competency', 'Community Care', 'Advocacy'],
    yearsExperience: 11,
    rating: 4.8,
    shiftsCompleted: 198,
    hourlyRate: { min: 17, max: 20 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '15',
    initials: 'YT',
    name: 'Yuki T.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Oxford',
    specialties: ['Infection Prevention', 'PPE Compliance', 'Cleaning Protocols'],
    yearsExperience: 3,
    rating: 4.5,
    shiftsCompleted: 72,
    hourlyRate: { min: 12.71, max: 14 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '16',
    initials: 'OW',
    name: 'Oliver W.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Portsmouth',
    specialties: ['Orthopedic Care', 'Pain Management', 'Physiology'],
    yearsExperience: 9,
    rating: 4.8,
    shiftsCompleted: 134,
    hourlyRate: { min: 24, max: 28 },
    availability: 'Mon-Fri',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '17',
    initials: 'MF',
    name: 'Margot F.',
    role: 'Support Worker',
    band: 'Band 2',
    location: 'Bath',
    specialties: ['Dementia Support', 'Activities', 'Recreation'],
    yearsExperience: 4,
    rating: 4.6,
    shiftsCompleted: 62,
    hourlyRate: { min: 13, max: 14.50 },
    availability: 'Weekends',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '18',
    initials: 'AJ',
    name: 'Aisha J.',
    role: 'Registered Nurse',
    band: 'Band 7',
    location: 'Newcastle',
    specialties: ['Infectious Disease', 'Infection Control', 'Training Lead'],
    yearsExperience: 16,
    rating: 4.9,
    shiftsCompleted: 211,
    hourlyRate: { min: 28, max: 31 },
    availability: 'Mon-Fri, Emergency Cover',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '19',
    initials: 'GC',
    name: 'George C.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Coventry',
    specialties: ['Patient Transport', 'Equipment Handling', 'Logistics'],
    yearsExperience: 2,
    rating: 4.4,
    shiftsCompleted: 41,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '20',
    initials: 'HB',
    name: 'Helen B.',
    role: 'Senior Registered Nurse',
    band: 'Band 8',
    location: 'Norwich',
    specialties: ['Leadership', 'Quality Assurance', 'Strategic Planning'],
    yearsExperience: 22,
    rating: 4.9,
    shiftsCompleted: 289,
    hourlyRate: { min: 32, max: 36 },
    availability: 'On-call, Strategic Consulting',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '21',
    initials: 'SR',
    name: 'Sarah R.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Liverpool',
    specialties: ['Elderly Care', 'Dementia', 'Palliative Support'],
    yearsExperience: 9,
    rating: 4.8,
    shiftsCompleted: 167,
    hourlyRate: { min: 24, max: 28 },
    availability: 'Mon-Fri, Weekends',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '22',
    initials: 'MW',
    name: 'Michael W.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Swansea',
    specialties: ['Patient Care', 'Mobility Support', 'Hygiene Assistance'],
    yearsExperience: 2,
    rating: 4.5,
    shiftsCompleted: 54,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '23',
    initials: 'CM',
    name: 'Catherine M.',
    role: 'Senior Care Worker',
    band: 'Band 3',
    location: 'Belfast',
    specialties: ['Residential Care', 'Dementia Support', 'Activity Planning'],
    yearsExperience: 11,
    rating: 4.7,
    shiftsCompleted: 234,
    hourlyRate: { min: 15, max: 17 },
    availability: 'Weekends, Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '24',
    initials: 'KM',
    name: 'Kevin M.',
    role: 'Support Worker',
    band: 'Band 2',
    location: 'Aberdeen',
    specialties: ['Mental Health Support', 'Community Care', 'Safeguarding'],
    yearsExperience: 5,
    rating: 4.6,
    shiftsCompleted: 108,
    hourlyRate: { min: 13, max: 14.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '25',
    initials: 'JN',
    name: 'Jane N.',
    role: 'Registered Nurse',
    band: 'Band 7',
    location: 'Coventry',
    specialties: ['Infection Control', 'Training', 'Clinical Leadership'],
    yearsExperience: 17,
    rating: 4.9,
    shiftsCompleted: 245,
    hourlyRate: { min: 29, max: 33 },
    availability: 'Mon-Fri, Emergency Cover',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '26',
    initials: 'DM',
    name: 'Douglas M.',
    role: 'Nursing Assistant',
    band: 'Band 2',
    location: 'Reading',
    specialties: ['Patient Hygiene', 'Feeding Support', 'Bed Management'],
    yearsExperience: 3,
    rating: 4.5,
    shiftsCompleted: 67,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '27',
    initials: 'PC',
    name: 'Patricia C.',
    role: 'Senior Registered Nurse',
    band: 'Band 8',
    location: 'Wakefield',
    specialties: ['Leadership', 'Quality Improvement', 'Staff Development'],
    yearsExperience: 24,
    rating: 4.9,
    shiftsCompleted: 312,
    hourlyRate: { min: 33, max: 38 },
    availability: 'On-call, Strategic Consulting',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '28',
    initials: 'AB',
    name: 'Andrew B.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Chelmsford',
    specialties: ['Physical Care', 'Dementia Support', 'Recreation'],
    yearsExperience: 4,
    rating: 4.4,
    shiftsCompleted: 79,
    hourlyRate: { min: 12.71, max: 14 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '29',
    initials: 'FM',
    name: 'Fiona M.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Dunfermline',
    specialties: ['Palliative Care', 'Pain Management', 'Family Support'],
    yearsExperience: 10,
    rating: 4.8,
    shiftsCompleted: 178,
    hourlyRate: { min: 25, max: 29 },
    availability: 'Mon-Fri, Weekends',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '30',
    initials: 'RC',
    name: 'Robert C.',
    role: 'Care Coordinator',
    band: 'Band 3',
    location: 'Newport',
    specialties: ['Shift Planning', 'Staff Management', 'Care Documentation'],
    yearsExperience: 7,
    rating: 4.6,
    shiftsCompleted: 112,
    hourlyRate: { min: 14, max: 16 },
    availability: 'Mon-Fri',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '31',
    initials: 'LS',
    name: 'Laura S.',
    role: 'Senior Care Worker',
    band: 'Band 4',
    location: 'Sheffield',
    specialties: ['Behavioral Support', 'Rehabilitation', 'Community Integration'],
    yearsExperience: 13,
    rating: 4.8,
    shiftsCompleted: 221,
    hourlyRate: { min: 18, max: 21 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '32',
    initials: 'NB',
    name: 'Nathan B.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Sunderland',
    specialties: ['Memory Care', 'End of Life', 'Family Counseling'],
    yearsExperience: 8,
    rating: 4.7,
    shiftsCompleted: 145,
    hourlyRate: { min: 24, max: 28 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '33',
    initials: 'TK',
    name: 'Theresa K.',
    role: 'Support Worker',
    band: 'Band 2',
    location: 'Slough',
    specialties: ['Dementia Care', 'Emotional Support', 'Daily Living'],
    yearsExperience: 6,
    rating: 4.5,
    shiftsCompleted: 98,
    hourlyRate: { min: 13, max: 14 },
    availability: 'Weekends, Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '34',
    initials: 'WL',
    name: 'William L.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Inverness',
    specialties: ['Elderly Care', 'Rehabilitation', 'Equipment Support'],
    yearsExperience: 3,
    rating: 4.4,
    shiftsCompleted: 71,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '35',
    initials: 'GF',
    name: 'Gemma F.',
    role: 'Registered Nurse',
    band: 'Band 7',
    location: 'Durham',
    specialties: ['Dementia Specialist', 'Training Lead', 'Clinical Governance'],
    yearsExperience: 16,
    rating: 4.8,
    shiftsCompleted: 198,
    hourlyRate: { min: 28, max: 31 },
    availability: 'Mon-Fri, Emergency Cover',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '36',
    initials: 'JB',
    name: 'Jonathan B.',
    role: 'Nursing Assistant',
    band: 'Band 2',
    location: 'Bangor',
    specialties: ['Patient Support', 'Hygiene Care', 'Meal Service'],
    yearsExperience: 2,
    rating: 4.3,
    shiftsCompleted: 45,
    hourlyRate: { min: 12.71, max: 13 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '37',
    initials: 'EM',
    name: 'Emma M.',
    role: 'Senior Care Worker',
    band: 'Band 4',
    location: 'Derry',
    specialties: ['Learning Disabilities', 'Advocacy', 'Community Support'],
    yearsExperience: 12,
    rating: 4.7,
    shiftsCompleted: 203,
    hourlyRate: { min: 17, max: 20 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '38',
    initials: 'PM',
    name: 'Peter M.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Stoke',
    specialties: ['Mental Health Support', 'Acute Care', 'Documentation'],
    yearsExperience: 11,
    rating: 4.8,
    shiftsCompleted: 189,
    hourlyRate: { min: 24, max: 27 },
    availability: 'Mon-Fri, On-call',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '39',
    initials: 'VH',
    name: 'Vanessa H.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Bournemouth',
    specialties: ['Personal Care', 'Mobility Support', 'Companionship'],
    yearsExperience: 4,
    rating: 4.6,
    shiftsCompleted: 86,
    hourlyRate: { min: 12.71, max: 14 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '40',
    initials: 'QS',
    name: 'Quincy S.',
    role: 'Senior Registered Nurse',
    band: 'Band 7',
    location: 'Lincoln',
    specialties: ['Leadership', 'Dementia Care', 'Staff Training'],
    yearsExperience: 20,
    rating: 4.9,
    shiftsCompleted: 267,
    hourlyRate: { min: 28, max: 32 },
    availability: 'On-call, Flexible',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '41',
    initials: 'UM',
    name: 'Uma M.',
    role: 'Support Worker',
    band: 'Band 2',
    location: 'Perth',
    specialties: ['Dementia Support', 'Activity Facilitation', 'Care Duties'],
    yearsExperience: 5,
    rating: 4.5,
    shiftsCompleted: 94,
    hourlyRate: { min: 13, max: 14.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '42',
    initials: 'XL',
    name: 'Xavier L.',
    role: 'Care Coordinator',
    band: 'Band 4',
    location: 'Swindon',
    specialties: ['Scheduling', 'Staff Coordination', 'Quality Monitoring'],
    yearsExperience: 8,
    rating: 4.6,
    shiftsCompleted: 135,
    hourlyRate: { min: 17, max: 20 },
    availability: 'Mon-Fri',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '43',
    initials: 'YB',
    name: 'Yasmine B.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Armagh',
    specialties: ['Memory Care', 'Family Support', 'Care Planning'],
    yearsExperience: 9,
    rating: 4.8,
    shiftsCompleted: 154,
    hourlyRate: { min: 25, max: 28 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '44',
    initials: 'ZK',
    name: 'Zachary K.',
    role: 'Nursing Assistant',
    band: 'Band 2',
    location: 'Wolverhampton',
    specialties: ['Patient Hygiene', 'Rehabilitation Support', 'Equipment Care'],
    yearsExperience: 3,
    rating: 4.4,
    shiftsCompleted: 68,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '45',
    initials: 'IG',
    name: 'Isabel G.',
    role: 'Senior Care Worker',
    band: 'Band 3',
    location: 'Medway',
    specialties: ['Dementia Care', 'Behavioral Support', 'Activity Coordination'],
    yearsExperience: 14,
    rating: 4.7,
    shiftsCompleted: 256,
    hourlyRate: { min: 16, max: 18 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '46',
    initials: 'AK',
    name: 'Alison K.',
    role: 'Registered Nurse',
    band: 'Band 7',
    location: 'Stirling',
    specialties: ['Stroke Care', 'Rehabilitation', 'Training Leadership'],
    yearsExperience: 18,
    rating: 4.9,
    shiftsCompleted: 223,
    hourlyRate: { min: 29, max: 32 },
    availability: 'Mon-Fri, Emergency Cover',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '47',
    initials: 'BC',
    name: 'Brandon C.',
    role: 'Live-in Carer',
    band: 'N/A',
    location: 'Cardiff',
    specialties: ['Live-in Care', '24/7 Support', 'Personal Assistance'],
    yearsExperience: 7,
    rating: 4.8,
    shiftsCompleted: 92,
    hourlyRate: { min: 19, max: 23 },
    availability: 'Live-in',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '48',
    initials: 'CP',
    name: 'Christine P.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Wigan',
    specialties: ['Elderly Care', 'Domestic Support', 'Laundry Services'],
    yearsExperience: 5,
    rating: 4.5,
    shiftsCompleted: 89,
    hourlyRate: { min: 13, max: 14.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '49',
    initials: 'DD',
    name: 'Diana D.',
    role: 'Senior Registered Nurse',
    band: 'Band 8',
    location: 'Northampton',
    specialties: ['Strategic Leadership', 'Quality Assurance', 'Care Excellence'],
    yearsExperience: 23,
    rating: 4.9,
    shiftsCompleted: 298,
    hourlyRate: { min: 32, max: 37 },
    availability: 'On-call, Strategic Consulting',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '50',
    initials: 'EV',
    name: 'Ethan V.',
    role: 'Support Worker',
    band: 'Band 2',
    location: 'Falkirk',
    specialties: ['Dementia Support', 'Companionship', 'Activity Support'],
    yearsExperience: 4,
    rating: 4.5,
    shiftsCompleted: 76,
    hourlyRate: { min: 12.71, max: 14 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '51',
    initials: 'FR',
    name: 'Francesca R.',
    role: 'Registered Nurse',
    band: 'Band 6',
    location: 'Wrexham',
    specialties: ['Stroke Recovery', 'Physical Rehabilitation', 'Family Education'],
    yearsExperience: 10,
    rating: 4.8,
    shiftsCompleted: 172,
    hourlyRate: { min: 24, max: 28 },
    availability: 'Mon-Fri, Weekends',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '52',
    initials: 'GH',
    name: 'Gregory H.',
    role: 'Care Coordinator',
    band: 'Band 4',
    location: 'Lisburn',
    specialties: ['Shift Coordination', 'Staff Training', 'Care Auditing'],
    yearsExperience: 9,
    rating: 4.7,
    shiftsCompleted: 147,
    hourlyRate: { min: 18, max: 21 },
    availability: 'Mon-Fri',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '53',
    initials: 'HT',
    name: 'Hannah T.',
    role: 'Healthcare Assistant',
    band: 'Band 2',
    location: 'Ipswich',
    specialties: ['Personal Care', 'Meal Support', 'Housekeeping'],
    yearsExperience: 2,
    rating: 4.4,
    shiftsCompleted: 52,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
  {
    id: '54',
    initials: 'IW',
    name: 'Iris W.',
    role: 'Senior Registered Nurse',
    band: 'Band 7',
    location: 'Peterborough',
    specialties: ['Memory Care Leadership', 'Dementia Specialist', 'Staff Development'],
    yearsExperience: 19,
    rating: 4.9,
    shiftsCompleted: 256,
    hourlyRate: { min: 29, max: 33 },
    availability: 'Flexible, On-call',
    verified: true,
    nmcVerified: true,
    dbsVerified: true,
  },
  {
    id: '55',
    initials: 'JO',
    name: 'Joshua O.',
    role: 'Nursing Assistant',
    band: 'Band 2',
    location: 'Paisley',
    specialties: ['Patient Care', 'Wound Dressing Support', 'Feeding Assistance'],
    yearsExperience: 3,
    rating: 4.5,
    shiftsCompleted: 65,
    hourlyRate: { min: 12.71, max: 13.50 },
    availability: 'Flexible',
    verified: true,
    nmcVerified: false,
    dbsVerified: true,
  },
];
